# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

services:
  githubmcpserver:
    image: githubmcpserver
    build:
      context: .
      dockerfile: GitHubMcpServer/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 5000:5000
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - GITHUB_TOKEN
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
